In [2]:
import numpy as np

In [2]:
a = np.array([[0,1],[0,1]])
print a
# print a[0]
# print a[:,1]
print np.mean(a,axis=0)

[[0 1]
 [0 1]]
[ 0.  1.]


In [3]:
np.dot([0,1],a)

array([0, 1])

In [4]:
np.dot(a,[0,1])

array([1, 1])

In [11]:
np.linalg.norm([2,2],16)

2.0885475648548275

In [12]:
A = np.array(([1,2],[3,4]))
B = np.array([5,6])
np.dot(A,B)

array([17, 39])